import { Book } from "@/models/book.models";
import { Testimonial } from "@/models/user.models";

export const MOCKED_BOOK_1: Book = {
  id: "1",
  title: "Mocked Book",
  description:
    "Le roman suit les destins croisés de plusieurs personnages, mais se concentre principalement sur Jean Valjean, un ancien forçat condamné pour vol de pain qui devient un homme intègre, et sur l'inspecteur Javert, déterminé à le ramener à la justice.\nL'histoire se déroule dans la France du 19ème siècle, couvrant des événements historiques comme la révolution de 1832. À travers ces personnages et événements, Hugo explore des thèmes universels tels que la rédemption, l'amour, la misère et l'injustice sociale.",
  author: "Mocked Author",
  cover: "/img/woman_studying.png",
  favorite: false,
  styles: ["Mocked Style", "Mocked Style 2", "Mocked Style 3"],
  rating: 4.6,
  reviews: [
    {
      reviewId: "1",
      userId: "1",
      username: "PDG",
      firstName: "Naheem",
      lastName: "Akaby",
      status: "STUDENT",
      bookId: "1",
      rating: 5,
      comment: "Mocked Comment",
      language: "fr",
      createdAt: "2022-01-01",
    },
    {
      reviewId: "2",
      userId: "2",
      username: "RacistePrime",
      firstName: "Imed",
      lastName: "Zarour",
      status: "STUDENT",
      bookId: "2",
      rating: 4,
      comment: "Mocked Comment",
      language: "fr",
      createdAt: "2022-01-01",
    },{
      reviewId: "3",
      userId: "3",
      username: "example",
      firstName: "John",
      lastName: "Doe",
      status: "TEACHER",
      bookId: "3",
      rating: 4,
      comment: "Mocked Comment",
      language: "fr",
      createdAt: "2022-01-01",
    },
  ],
  price: 3,
  owner: {
    userId: "Mocked Owner",
    username: "Mocked Owner",
    email: "Mocked Owner",
    firstName: "Mocked Owner",
    lastName: "Mocked Owner",
    status: "WORKER",
    createdAt: new Date(),
    updatedAt: new Date(),
    bookIds: [],
    reviewIds: [],
    testimonialIds: [],
    favoriteIds: [],
    loanedBookIds: [],    
  },
  information: {
    pages: 100,
    year: 2022,
    language: "FR",
    delivery: "FREE",
  },
  loaned: false,
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const MOCKED_BOOK_2: Book = {
  id: "2",
  title: "Mocked Book",
  description:
    "Le roman suit les destins croisés de plusieurs personnages, mais se concentre principalement sur Jean Valjean, un ancien forçat condamné pour vol de pain qui devient un homme intègre, et sur l'inspecteur Javert, déterminé à le ramener à la justice.\nL'histoire se déroule dans la France du 19ème siècle, couvrant des événements historiques comme la révolution de 1832. À travers ces personnages et événements, Hugo explore des thèmes universels tels que la rédemption, l'amour, la misère et l'injustice sociale.",
  author: "Mocked Author",
  cover: "/img/woman_studying.png",
  favorite: false,
  styles: ["Mocked Style", "Mocked Style 2", "Mocked Style 3"],
  rating: 4.6,
  reviews: [
    {
      reviewId: "1",
      userId: "1",
      username: "PDG",
      firstName: "Naheem",
      lastName: "Akaby",
      status: "STUDENT",
      bookId: "1",
      rating: 5,
      comment: "Mocked Comment",
      language: "fr",
      createdAt: "2022-01-01",
    },
    {
      reviewId: "2",
      userId: "2",
      username: "RacistePrime",
      firstName: "Imed",
      lastName: "Zarour",
      status: "STUDENT",
      bookId: "2",
      rating: 4,
      comment: "Mocked Comment",
      language: "fr",
      createdAt: "2022-01-01",
    },{
      reviewId: "3",
      userId: "3",
      username: "example",
      firstName: "John",
      lastName: "Doe",
      status: "TEACHER",
      bookId: "3",
      rating: 4,
      comment: "Mocked Comment",
      language: "fr",
      createdAt: "2022-01-01",
    },
  ],
  price: 3,
  owner: {
    userId: "Mocked Owner",
    username: "Mocked Owner",
    email: "Mocked Owner",
    firstName: "Mocked Owner",
    lastName: "Mocked Owner",
    status: "WORKER",
    createdAt: new Date(),
    updatedAt: new Date(),
    bookIds: [],
    reviewIds: [],
    testimonialIds: [],
    favoriteIds: [],
    loanedBookIds: [],    
  },
  information: {
    pages: 100,
    year: 2022,
    language: "FR",
    delivery: "FREE",
  },
  loaned: false,
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const MOCKED_BOOK_3: Book = {
  id: "3",
  title: "Mocked Book",
  description:
    "Le roman suit les destins croisés de plusieurs personnages, mais se concentre principalement sur Jean Valjean, un ancien forçat condamné pour vol de pain qui devient un homme intègre, et sur l'inspecteur Javert, déterminé à le ramener à la justice.\nL'histoire se déroule dans la France du 19ème siècle, couvrant des événements historiques comme la révolution de 1832. À travers ces personnages et événements, Hugo explore des thèmes universels tels que la rédemption, l'amour, la misère et l'injustice sociale.",
  author: "Mocked Author",
  cover: "/img/woman_studying.png",
  favorite: false,
  styles: ["Mocked Style", "Mocked Style 2", "Mocked Style 3"],
  rating: 4.6,
  reviews: [
    {
      reviewId: "1",
      userId: "1",
      username: "PDG",
      firstName: "Naheem",
      lastName: "Akaby",
      status: "STUDENT",
      bookId: "1",
      rating: 5,
      comment: "Mocked Comment",
      language: "fr",
      createdAt: "2022-01-01",
    },
    {
      reviewId: "2",
      userId: "2",
      username: "RacistePrime",
      firstName: "Imed",
      lastName: "Zarour",
      status: "STUDENT",
      bookId: "2",
      rating: 4,
      comment: "Mocked Comment",
      language: "fr",
      createdAt: "2022-01-01",
    },{
      reviewId: "3",
      userId: "3",
      username: "example",
      firstName: "John",
      lastName: "Doe",
      status: "TEACHER",
      bookId: "3",
      rating: 4,
      comment: "Mocked Comment",
      language: "fr",
      createdAt: "2022-01-01",
    },
  ],
  price: 3,
  owner: {
    userId: "Mocked Owner",
    username: "Mocked Owner",
    email: "Mocked Owner",
    firstName: "Mocked Owner",
    lastName: "Mocked Owner",
    status: "WORKER",
    createdAt: new Date(),
    updatedAt: new Date(),
    bookIds: [],
    reviewIds: [],
    testimonialIds: [],
    favoriteIds: [],
    loanedBookIds: [],    
  },
  information: {
    pages: 100,
    year: 2022,
    language: "FR",
    delivery: "FREE",
  },
  loaned: false,
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const MOCKED_BOOK_4: Book = {
  id: "4",
  title: "Mocked Book",
  description:
    "Le roman suit les destins croisés de plusieurs personnages, mais se concentre principalement sur Jean Valjean, un ancien forçat condamné pour vol de pain qui devient un homme intègre, et sur l'inspecteur Javert, déterminé à le ramener à la justice.\nL'histoire se déroule dans la France du 19ème siècle, couvrant des événements historiques comme la révolution de 1832. À travers ces personnages et événements, Hugo explore des thèmes universels tels que la rédemption, l'amour, la misère et l'injustice sociale.",
  author: "Mocked Author",
  cover: "/img/woman_studying.png",
  favorite: false,
  styles: ["Mocked Style", "Mocked Style 2", "Mocked Style 3"],
  rating: 4.6,
  reviews: [
    {
      reviewId: "1",
      userId: "1",
      username: "PDG",
      firstName: "Naheem",
      lastName: "Akaby",
      status: "STUDENT",
      bookId: "1",
      rating: 5,
      comment: "Mocked Comment",
      language: "fr",
      createdAt: "2022-01-01",
    },
    {
      reviewId: "2",
      userId: "2",
      username: "RacistePrime",
      firstName: "Imed",
      lastName: "Zarour",
      status: "STUDENT",
      bookId: "2",
      rating: 4,
      comment: "Mocked Comment",
      language: "fr",
      createdAt: "2022-01-01",
    },{
      reviewId: "3",
      userId: "3",
      username: "example",
      firstName: "John",
      lastName: "Doe",
      status: "TEACHER",
      bookId: "3",
      rating: 4,
      comment: "Mocked Comment",
      language: "fr",
      createdAt: "2022-01-01",
    },
  ],
  information: {
    pages: 100,
    year: 2022,
    language: "FR",
    delivery: "FREE",
  },
  price: 3,
  owner: {
    userId: "Mocked Owner",
    username: "Mocked Owner",
    email: "Mocked Owner",
    firstName: "Mocked Owner",
    lastName: "Mocked Owner",
    status: "WORKER",
    createdAt: new Date(),
    updatedAt: new Date(),
    bookIds: [],
    reviewIds: [],
    testimonialIds: [],
    favoriteIds: [],
    loanedBookIds: [],    
  },
  loaned: false,
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const MOCKED_BOOKS: Book[] = [
  MOCKED_BOOK_1,
  MOCKED_BOOK_2,
  MOCKED_BOOK_3,
  MOCKED_BOOK_4,
];

export const TESTIMONIALS_MOCK_FR: Testimonial[] = [
  {
    testimonialId: "1",
    userId: "1",
    username: "PDG",
    firstName: "Naheem",
    lastName: "Akaby",
    status: "STUDENT",
    rating: 5,
    comment:
      "Liprêrie a transformé ma façon de découvrir de nouveaux livres. Le choix est incroyable et la livraison est toujours ponctuelle. J'ai lu plus de livres cette année que jamais auparavant !",
    createdAt: "2022-01-01",
    language: "fr",
  },
  {
    testimonialId: "2",
    userId: "2",
    username: "RacistePrime",
    firstName: "Imed",
    lastName: "Zarour",
    status: "STUDENT",
    rating: 4,
    comment:
      "Enfin un service de prêt de livres qui comprend les lecteurs ! Pas de désordre, pas de tracas. J’adore pouvoir rendre les livres sans stress et avoir toujours quelque chose de nouveau à lire.",
    createdAt: "2022-01-01",
    language: "fr",
  },
  {
    testimonialId: "3",
    userId: "3",
    username: "example",
    firstName: "John",
    lastName: "Doe",
    status: "TEACHER",
    rating: 4,
    comment:
      "Notre club de lecture est entièrement passé à Liprêrie. Tout le monde reçoit ses exemplaires à temps et nous économisons énormément d'argent !",
    createdAt: "2022-01-01",
    language: "fr",
  },
];

export const TESTIMONIALS_MOCK_EN: Testimonial[] = [
  {
    testimonialId: "4",
    userId: "1",
    username: "PDG",
    firstName: "Naheem",
    lastName: "Akaby",
    status: "STUDENT",
    rating: 5,
    comment:
      "Liprêrie has transformed the way I discover new books. The selection is incredible and the delivery is always on time. I've read more books this year than ever before!",
    createdAt: "2022-01-01",
    language: "en",
  },
  {
    testimonialId: "5",
    userId: "2",
    username: "RacistePrime",
    firstName: "Imed",
    lastName: "Zarour",
    status: "STUDENT",
    rating: 4,
    comment:
      "Finally, a book lending service that understands readers! No mess, no hassle. I love being able to return books stress-free and always have something new to read.",
    createdAt: "2022-01-01",
    language: "en",
  },
  {
    testimonialId: "6",
    userId: "3",
    username: "example",
    firstName: "John",
    lastName: "Doe",
    status: "TEACHER",
    rating: 4,
    comment:
      "Our book club has completely switched to Liprêrie. Everyone receives their copies on time and we're saving a lot of money!",
    createdAt: "2022-01-01",
    language: "en",
  },
];
